### ISSUE TITLE
What is its primary usecase?

### ISSUE THREAD

**Issue by bhanuvrat** [corsecotech/db_sync_tool#6]
The docs should highlight:

 - What does this tool do that can't be done by an ansible playbook?

**Comment by aniketmaithani** [comment]
Primary Use-Case : 
- So basically as the name suggest you can it can be used to `sync` the local DB on your machine and on the cloud. Much more like what rsync or any other utility would do. The problem which we are trying to address is `POSTGRES` specific tools are bit complex to use especially when it comes to taking the backup or syncing remote and local db. What this tool does is basically acts like a `plug and play`suite and can easily do the work with minimum set of dependencies and configuration. 
HTH.

**Comment by bhanuvrat** [comment]
@aniketmaithani 

Did you mean, keep your development machine in sync with the production data?

**Comment by aniketmaithani** [comment]
@bhanuvrat in our case. Local DB corresponds to the machine running PSQL on our hardware at Client's location [company specific hardware for video analysis] and once it gets flooded with 24hours of data it then automatically syncs the entire stuff to remote DB. [in this way consumes less bandwidth] and data sync is easy and then we flushes out the data from the local machine and again the process is repeated. 

Hope I am clear. :)

**Comment by bhanuvrat** [comment]
oh okay.
I wonder if you need Postgres on the client location.
Lets continue this over call.
